package darling.context.event;

public enum Event {
    CONTEXT_INIT,
    CONTEXT_CLOSED,
    CONTEXT_REFRESHED,
    CLOSE_DAY,
    LAST_PRICES_UPDATED,
    MAIN_SHARES_UPDATED,
    OPERATION_UPDATED,
    ORDER_POSTED,
    POSITION_UPDATED,
    PORTFOLIO_REFRESHED,
    CLOSED_DEALS_UPDATED
}