package darling.context.event;

public enum Event {
    CONTEXT_INITIALIZED,
    CONTEXT_REFRESHED,
    MAIN_SHARES_UPDATED,
    OPERATION_UPDATED,
    ORDER_POSTED,
    POSITION_UPDATED,
    PORTFOLIO_REFRESHED,
    CLOSED_DEALS_UPDATED
}